In [117]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [52]:
pd.__version__

'3.0.5'

In [53]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [54]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [55]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [56]:
df.fuel_type.nunique()

3

In [57]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [58]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [59]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [85]:
median_val = df.horsepower.median()

In [86]:
median_val

np.float64(254.0)

In [61]:
freq_val = df.horsepower.mode()

In [62]:
freq_val

0    252.0
Name: horsepower, dtype: float64

In [63]:
df.horsepower.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [92]:
updating_median = df.horsepower.fillna(freq_val).median()

In [93]:
updating_median

np.float64(254.0)

In [87]:
df.horsepower.isnull().value_counts()

horsepower
False    9123
True      877
Name: count, dtype: int64

In [89]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [106]:
cars = df[df['origin'] == 'Asia'][['model_year','vehicle_weight']]

In [107]:
cars

      model_year  vehicle_weight
2           1996            4240
6           1992            4310
8           1997            4230
10          1978            4420
15          2007            3950
...          ...             ...
9984        2011            4610
9987        2004            4530
9990        1975            3630
9994        1993            4610
9996        1993            4370

[2994 rows x 2 columns]

In [108]:
cars = cars.head(7)

In [109]:
cars

    model_year  vehicle_weight
2         1996            4240
6         1992            4310
8         1997            4230
10        1978            4420
15        2007            3950
16        2021            4750
22        2019            4450

In [110]:
X = cars.values

In [111]:
X

array([[1996, 4240],
       [1992, 4310],
       [1997, 4230],
       [1978, 4420],
       [2007, 3950],
       [2021, 4750],
       [2019, 4450]])

In [112]:
X.shape

(7, 2)

In [121]:
XTX = X.T.dot(X)

In [122]:
XTX

array([[ 28041424,  60750580],
       [ 60750580, 131950500]])

In [123]:
inv_XTX = np.linalg.inv(XTX)

In [124]:
inv_XTX

array([[ 1.39675281e-05, -6.43071025e-06],
       [-6.43071025e-06,  2.96830537e-06]])

In [125]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [126]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [128]:
w = inv_XTX.dot(X.T)

In [129]:
w

array([[ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04],
       [-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04]])

In [130]:
w = w * y

In [131]:
w

array([[ 0.67427208,  0.13904122,  0.5529994 , -0.71637186,  2.63152339,
        -2.54924935, -0.49946567],
       [-0.27509119, -0.02155228, -0.22895733,  0.35996837, -1.18162927,
         1.21328359,  0.27042587]])

In [132]:
w.sum()

np.float64(0.36919696904926846)